S2B-Final/Controllers/DenunciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S2B_Final.Data.Repositories.Interfaces;
using S2B_Final.Data.Repositories.Implementation;
using S2B_Final.Models;
using AutoMapper;

namespace S2B_Final.Controllers
{
    public class DenunciaController : Controller
    {
        private readonly IDenunciaRepository _denunciaRepository;
        public DenunciaController()
        {
            this._denunciaRepository = new DenunciaRepository(new Data.UO.UnitOfWork());
        }

        // GET: Denuncia
        public ActionResult Index()
        {
            var modelo = Mapper.Map<List<DenunciaModel>, List<DenunciaDisplayViewModel>>(_denunciaRepository.GetAll().ToList());
            return View(modelo);
        }

        // GET: Denuncia/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Denuncia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Denuncia/Create
        [HttpPost]
        public ActionResult Create(DenunciaCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                DenunciaModel aluno = Mapper.Map<DenunciaCreateViewModel, DenunciaModel>(model);
                this._denunciaRepository.Add(aluno);

                List<DenunciaModel> lista = new List<DenunciaModel>();
                lista = _denunciaRepository.GetAll().OrderBy(u => u.ID).ToList();
                var modelo = Mapper.Map<List<DenunciaModel>, List<DenunciaDisplayViewModel>>(lista);

                return View("Index", modelo);

            }
            else
            {
                return View();
            }
        }

        // GET: Denuncia/Edit/5
        public ActionResult Edit(int id)
        {
            var modelo = Mapper.Map<DenunciaModel, DenunciaEditViewModel>(_denunciaRepository.GetById(id));
            return View(modelo);
        }

        // POST: Denuncia/Edit/5
        [HttpPost]
        public ActionResult Edit(DenunciaEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                DenunciaModel aluno = Mapper.Map<DenunciaEditViewModel, DenunciaModel>(model);
                this._denunciaRepository.Update(aluno);

                List<DenunciaModel> lista = new List<DenunciaModel>();
                lista = _denunciaRepository.GetAll().OrderBy(u => u.ID).ToList();
                var modelo = Mapper.Map<List<DenunciaModel>, List<DenunciaDisplayViewModel>>(lista);

                return View("Index", modelo);

            }
            else
            {
                return View();
            }
        }

        // GET: Denuncia/Delete/5
        public ActionResult Delete(int id)
        {
            var modelo = Mapper.Map<DenunciaModel, DenunciaDeleteViewModel>(_denunciaRepository.GetById(id));
            return View(modelo);
        }

        // POST: Denuncia/Delete/5
        [HttpPost]
        public ActionResult Delete(DenunciaDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                DenunciaModel aluno = Mapper.Map<DenunciaDeleteViewModel, DenunciaModel>(model);
                this._denunciaRepository.Remove(aluno);

                List<DenunciaModel> lista = new List<DenunciaModel>();
                lista = _denunciaRepository.GetAll().OrderBy(u => u.ID).ToList();
                var modelo = Mapper.Map<List<DenunciaModel>, List<DenunciaDisplayViewModel>>(lista);

                return View("Index", modelo);

            }
            else
            {
                return View();
            }
        }

        public ActionResult Pesquisar(string searchBy, string search)
        {
            List<DenunciaModel> lista = new List<DenunciaModel>();
            switch (searchBy)
            {
                case "Local":
                    lista = _denunciaRepository.PesquisarPorLocal(search.Trim()).ToList();
                    break;
                default:
                    lista = _denunciaRepository.GetAll().OrderBy(u => u.ID).ToList();
                    break;
            }
            var modelo = Mapper.Map<List<DenunciaModel>, List<DenunciaDisplayViewModel>>(lista);
            return PartialView("_List", modelo);
        }
    }
}

S2B-Final/Views/Denuncia/Create.cshtml
@model S2B_Final.Models.DenunciaCreateViewModel

@{
    ViewBag.Title = "Cadastrar Nova Denuncia";
}

<link href="http://fonts.googleapis.com/css?family=Open+Sans:600" type="text/css" rel="stylesheet" />
<link href="~/GoogleMaps/estilo.css" type="text/css" rel="stylesheet" />


<h2>Cadastre uma nova Denúncia</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="form-group col-lg-6">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.TipoOcorrencia, htmlAttributes: new { @class = "control-label  col-md-4 " })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TipoOcorrencia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TipoOcorrencia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DescricaoOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DescricaoOcorrido,new { htmlAttributes = new { @class = "form-control " } } )
                    @Html.ValidationMessageFor(model => model.DescricaoOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DataOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HorarioOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.HorarioOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HorarioOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocalOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.LocalOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocalOcorrido, "", new { @class = "text-danger" })
                
                </div>
                
            </div>

         

            <div class="form-group">
                @Html.LabelFor(model => model.CaracteristicasSuspeito, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CaracteristicasSuspeito, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.CaracteristicasSuspeito, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.EditorFor(model => model.Ip, new { htmlAttributes = new { @class = "esconde" } })


            @Html.EditorFor(model => model.Navegador, new { htmlAttributes = new { @class = "esconde" } })

            @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "esconde" } })


            @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "esconde" } })



        </div>
        <div class="form-group col-lg-6">

            <div class="campos">
                <label for="mapa">Mapa:</label>

            </div>
            <div id="mapa"></div>

            <input type="hidden" id="txtLatitude" name="txtLatitude" />
            <input type="hidden" id="txtLongitude" name="txtLongitude" />

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-primary" /> |
                <a href="@Url.Action("Index","Denuncia")" class="btn btn-danger">Voltar</a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    var geocoder;
    var map;
    var marker;

    function initialize() {
        var latlng = new google.maps.LatLng(-18.8800397, -47.05878999999999);
        var options = {
            zoom: 5,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById("mapa"), options);

        geocoder = new google.maps.Geocoder();

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
        });

        marker.setPosition(latlng);
    }
</script>
<script type="text/javascript" src="~/GoogleMaps/mapa.js"></script>

S2B-Final/Views/Denuncia/Delete.cshtml
@model S2B_Final.Models.DenunciaDeleteViewModel

@{
    ViewBag.Title = "Excluir Denúncia";
}
<script type="text/javascript" src="~/GoogleMaps/mapa.js"></script>

<link href="http://fonts.googleapis.com/css?family=Open+Sans:600" type="text/css" rel="stylesheet" />
<link href="~/GoogleMaps/estilo.css" type="text/css" rel="stylesheet" />


<h2>Excluir Denúncia</h2>

<h3>Você tem certeza que deseja excluir?</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


<hr />
<div class="form-horizontal">
    <div class="form-group col-lg-6">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TipoOcorrencia, htmlAttributes: new { @class = "control-label  col-md-4 " })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.TipoOcorrencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoOcorrencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.DescricaoOcorrido, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.DescricaoOcorrido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.DataOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataOcorrido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorarioOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.HorarioOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorarioOcorrido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.LocalOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalOcorrido, "", new { @class = "text-danger" })
              
            </div>

        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.CaracteristicasSuspeito, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.DisplayFor(model => model.CaracteristicasSuspeito, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.CaracteristicasSuspeito, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Ip, new { htmlAttributes = new { @class = "esconde" } })


        @Html.HiddenFor(model => model.Navegador, new { htmlAttributes = new { @class = "esconde" } })

        @Html.HiddenFor(model => model.Latitude, new { htmlAttributes = new { @class = "esconde" } })


        @Html.HiddenFor(model => model.Longitude, new { htmlAttributes = new { @class = "esconde" } })



    </div>
    <div class="form-group col-lg-6">

        <div class="campos">
            <label for="mapa">Mapa:</label>

        </div>
        <div id="mapa"></div>

        <input type="hidden" id="txtLatitude" name="txtLatitude" />
        <input type="hidden" id="txtLongitude" name="txtLongitude" />

    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Excluir" class="btn btn-primary" /> |
            <a href="@Url.Action("Index", "Denuncia")" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
</div>

}

<script>
    var geocoder;
    var map;
    var marker;
    var latitude = document.getElementById("Latitude").value;
    var longitude = document.getElementById("Longitude").value;



    function initialize() {

        var latlng = new google.maps.LatLng(latitude, longitude);
        var options = {
            zoom: 16,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById("mapa"), options);

        geocoder = new google.maps.Geocoder();

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
        });

        marker.setPosition(latlng);
    }
</script>
<script type="text/javascript" src="~/GoogleMaps/mapa.js"></script>

S2B-Final/Views/Denuncia/Edit.cshtml
@model S2B_Final.Models.DenunciaEditViewModel

@{
    ViewBag.Title = "Editar Denúncia";
}

<script type="text/javascript" src="~/GoogleMaps/mapa.js"></script>


<link href="http://fonts.googleapis.com/css?family=Open+Sans:600" type="text/css" rel="stylesheet" />
<link href="~/GoogleMaps/estilo.css" type="text/css" rel="stylesheet" />

<h2>Editar Denúncia</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />
    <div class="form-horizontal">
        <div class="form-group col-lg-6">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.TipoOcorrencia, htmlAttributes: new { @class = "control-label  col-md-4 " })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TipoOcorrencia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TipoOcorrencia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DescricaoOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DescricaoOcorrido, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.DescricaoOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DataOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HorarioOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.HorarioOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HorarioOcorrido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocalOcorrido, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.LocalOcorrido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocalOcorrido, "", new { @class = "text-danger" })
              
                </div>

            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.CaracteristicasSuspeito, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CaracteristicasSuspeito, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.CaracteristicasSuspeito, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.EditorFor(model => model.Ip, new { htmlAttributes = new { @class = "esconde" } })


            @Html.EditorFor(model => model.Navegador, new { htmlAttributes = new { @class = "esconde" } })

            @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "esconde" } })


            @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "esconde" } })



        </div>
        <div class="form-group col-lg-6">

            <div class="campos">
                <label for="mapa">Mapa:</label>

            </div>
            <div id="mapa"></div>

            <input type="hidden" id="txtLatitude" name="txtLatitude" />
            <input type="hidden" id="txtLongitude" name="txtLongitude" />

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" /> |
                <a href="@Url.Action("Index","Denuncia")" class="btn btn-danger">Cancelar</a>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    var geocoder;
    var map;
    var marker;
    var latitude = document.getElementById("Latitude").value;
    var longitude = document.getElementById("Longitude").value;

   
  
    function initialize() {
       
        var latlng = new google.maps.LatLng(latitude, longitude);
        var options = {
            zoom: 16,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        
        map = new google.maps.Map(document.getElementById("mapa"), options);

        geocoder = new google.maps.Geocoder();

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
        });

        marker.setPosition(latlng);
    }
</script>
<script type="text/javascript" src="~/GoogleMaps/mapa.js"></script>

S2B-Final/Views/Denuncia/Index.cshtml
@model List<S2B_Final.Models.DenunciaDisplayViewModel>
@{
    ViewBag.Title = "Denúncias";
}

<h2>Lista de Denúncias</h2>


<div class="container">

    <div class="row container">
        <div id="addDenuncia" class="col-md-4 col-xs-12">
            <label class="control-label">Adicionar Denúncia</label>
            <button type="button" onclick="location.href='@Url.Action("Create","Denuncia")'" class="btn btn-success col-md-offset-1">
                <span class="glyphicon glyphicon-plus-sign"></span>
            </button>
        </div>
        <div class="visible-xs-block visible-sm"><hr /></div>
        <div id="pesquisaDiv" class="col-md-8 col-sm-8  col-xs-12 row container">
            <p class="col-md-3 col-sm-4 col-xs-12">
                <b>Pesquisar Por:</b>
            </p>
            <div class="row col-md-8 col-sm-8">
                <div class="col-md-3 col-sm-5  col-xs-12 radio-inline" style="margin-left:10px;">
                    @Html.RadioButton("searchBy", "Todos", true, new { @id = "rbTodos" })<text>Todos</text>
                </div>
                <div class="col-md-3 col-sm-5 col-xs-12 radio-inline">
                    @Html.RadioButton("searchBy", "Local", false, new { @id = "rbLocal" })<text>Local</text>
                </div>
            </div>

            <div class="col-md-9 col-md-offset-3 col-sm-12 col-sm-offset-0">
                <div class="input-group">
                    <input type="text" id="tbSearch" class="form-control" style="max-width:100%;" />
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-info" id="btnPesq">
                            <span class="glyphicon glyphicon-search">&nbsp;</span>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <hr />
    </div>
    <br /><br />

    <div id="listaDenuncia">
        @{Html.RenderPartial("_List", Model);}
    </div>
</div>
@section Scripts{


    <script type="text/javascript">
        $(document).ready(inicializaComponentes);
        function inicializaComponentes()
        {
            $("#btnPesq").click(pesquisar);

        }

        function pesquisar() {
            var tipoBusca = $("input[type='radio'][name='searchBy']:checked").val();
            var textoBusca = $("input[type='text']#tbSearch").val();

            $.ajax({
                type: "GET",
                url: "@Url.Action("Pesquisar", "Denuncia")",
                dataType: "text",
                data: { searchBy: tipoBusca, search: textoBusca },
                beforeSend: function () {
                    $("#btnPesq").prop('disabled', true);
                    $("#trLoadingResults").show();
                },
                complete: function () {
                },
                success: function (response) {
                },
                error: function (response) {
                }
            }).done(function (result) {
                $("#listaDenuncia").html(result);
                $("#btnPesq").prop('disabled', false);
                $("#trLoadingResults").hide();
            });
            return false;
        }

    </script>
}

S2B-Final/Views/Denuncia/_List.cshtml
@model List<S2B_Final.Models.DenunciaDisplayViewModel>
<div style="position:relative;">
    <table id="tableListEventos" class="table table-responsive  table-striped table-hover" style="border-bottom:0;">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Tipo de Denúncia")

                </th>
                <th>
                    @Html.DisplayName("Data")

                </th>
                <th>
                    @Html.DisplayName("Horário")

                </th>
               
                <th>
                    @Html.DisplayName("Local")

                </th>

                <th style="width:7%;">Editar</th>
                <th style="width:7%;">Remover</th>

            </tr>
        </thead>
        @if (Model == null || Model.Count == 0)
        {
            <tbody>
                <tr class="tableDataDisplay" id="noDataToDisplayInTable">
                    <td colspan="2">Nenhum resultado para o registro pesquisado.</td>
                </tr>
            </tbody>

        }
        else
        {

            <tbody>

                @foreach (var item in Model)
                {

                    <tr class="tableDataDisplay">
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoOcorrencia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataOcorrido)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HorarioOcorrido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LocalOcorrido)
                        </td>

                        <td style="max-width:5%;">
                            <a href="@Url.Action("Edit", "Denuncia", new { id = item.ID})" title="Editar">
                                <span class="glyphicon glyphicon-pencil center-block text-center" aria-hidden="true"></span>
                            </a>
                        </td>
                        <td style="max-width:5%;">
                            <a href="@Url.Action("Delete", "Denuncia", new { id = item.ID})" title="Remover">
                                <span class="glyphicon glyphicon-remove-circle center-block text-center" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                }
                @*<tr>
                        <td colspan="3" id="trLoadingResults" style="border-style:hidden;" hidden>
                            <img src="~/Content/images/ajax-loader.gif" class="img-responsive imagemLoading" alt="Carregando Registros..." />
                        </td>
                    </tr>*@
            </tbody>
            @*<tfoot style="border-style:hidden;">
                    <tr class="no-border">
                        <td colspan="3" id="PagerTableData" class="no-border">
                            @Html.PagedListPager(Model, page => Url.Action("Pesquisar", new { page, searchBy = @ViewBag.searchBy, search = @ViewBag.search }), (PagedListRenderOptions)ViewBag.pLRO)
                        </td>
                    </tr>
                </tfoot>*@

        }



    </table>

</div>
@section Scripts{


    <script type="text/javascript">
        $(document).ready(inicializaComponentes);
        function inicializaComponentes() {
            $("#btnPesq").click(pesquisar);
            $("#btnExcluir").click(excluir);
        }
        function excluir() {
            var idALuno =
            $.ajax({
                type: "POST",
                url: "@Url.Action("Delete", "Denuncia","ID" )"
            });
        }

        function pesquisar() {
            var tipoBusca = $("input[type='radio'][name='searchBy']:checked").val();
            var textoBusca = $("input[type='text']#tbSearch").val();

            $.ajax({
                type: "GET",
                url: "@Url.Action("Pesquisar", "Denuncia")",
                dataType: "text",
                data: { searchBy: tipoBusca, search: textoBusca },
                beforeSend: function () {
                    $("#btnPesq").prop('disabled', true);
                    $("#trLoadingResults").show();
                },
                complete: function () {
                },
                success: function (response) {
                },
                error: function (response) {
                }
            }).done(function (result) {
                $("#listaDenuncia").html(result);
                $("#btnPesq").prop('disabled', false);
                $("#trLoadingResults").hide();
            });
            return false;
        }

    </script>
}